.\" Peerio client
.\"
.TH Peerio Client 1 "FEBRUARY 2016" Linux "User Manuals"
.SH NAME
Peerio Client
.SH SYNOPSIS
.B peerio-client
.SH DESCRIPTION
.B peerio-client
is the client side of Peerio, a cloud storage
service based on miniLock, providing users with end-to-end
encryption.
.SH FILES
.I /usr/share/peerio-client
.RS
peerio client packaged with nwjs
.SH AUTHORS
Peerio-client is distributed and maintained by
PeerioTechnologies.
